GET http://localhost:3003/users
content-type: application/json

### 

GET http://localhost:3003/products
content-type: application/json

### 

GET http://localhost:3003/users/01/purchases
content-type: application/json

### 

POST http://localhost:3003/users
content-type: application/json

{
    "name": "Marta",
    "email": "marta@email.com",
    "password": "marta0010362"
}

### 

POST http://localhost:3003/products
content-type: application/json

{
    "name": "Camiseta Liverpool XPS Sports",
    "price": 64,
    "image_url": "https://imgcentauro-a.akamaihd.net/900x900/9713973I/camiseta-liverpool-xps-sports-masculina-warren-img.jpg"
}

### 

POST http://localhost:3003/purchases
content-type: application/json

{
    "user_id": "03",
    "product_id": "02",
    "quantity": 2
}

### 